# Model run parameters
data_dir: './data_uploads'
results_dir: './model_results'

# region number
region_no: 0

# scenario binary & technology availability
config: 0
# 0: only domestic load and no irrigation;
# 1: single farmer system.
# 2: irrigation zone has shared energy system;
# 3: config 2 plus MV, LV lines connect zones;
solar_ava: True
battery_la_ava: True
battery_li_ava: False
diesel_ava: True
diesel_vali_cond: True

# general model assumptions
irrgation_area_ratio: 1
num_year: 1
num_hours: 8760
i_rate: 0.128

# farmer data
sf_land_area: [5000]
dome_load_rate: 2     # 2kWh/ha/day

# Solar
solar_pw_cap_kw:  [0,5,   10,   50,   250,  1000, 2000]
solar_pw_cost_kw: [0,6680,11450,44550,183e3,573e3, 1146e3]
annualize_years_solar: 15
solar_min_cap: 0.2

# Battery. lc: lead-acid; li: li-ion.
battery_la_cost_kwh: 181
battery_la_eff: 0.894             # round way efficiency 80%
battery_la_min_soc: 0.4
annualize_years_battery_la: 5
battery_li_cost_kwh: 461   # low assumption as 150
battery_li_eff: 0.949             # round way efficiency 80%
battery_li_min_soc: 0.1
annualize_years_battery_li: 10
battery_start_level: 0.5

battery_inverter_cost_kw: 173
annualize_years_battery_inverter: 10
battery_la_p2e_ratio_range: [0.25, 0.25]
battery_li_p2e_ratio_range: [0.25, 0.25]   # seperate iverter for la, li here
nominal_charge_discharge_cost_kwh: 0.001

# Diesel
diesel_cap_cost_kw: 808
diesel_cost_liter: 1
diesel_min_cap: 0.5
liter_per_kwh: 0.094634 # diesel fuel energy density
diesel_eff: 0.3
annualize_years_diesel: 10

# transmission
trans_lv_cost_kw_m: 8.45
trans_mv_cost_kw_m: 16
annualize_years_trans: 15
transformer_cost: 5000
dist_lv_m_per_ha: 150

# Flexible load & pumps
irrigation_minimum_power: 0.5 # Minimum operation power is 1 kW
irrigation_maximum_power: 9999
first_season_start:  0     # Jul. 1
first_season_end:    122   # Oct. 31, which should be included in the season
second_season_start: 137   # Nov. 15
second_season_end:   257   # Mar. 15
no_irrigation_hours: [0,16,17,18,19,20,21,22,23]  # during these hours, there are no irrigation local time 7:30pm-3:30am
water_demand_kg_m2_day: 7  # 7 mm / m2*day
water_account_days: 5      # any 5-day period, water should be enough
irrigation_kwh_p_kg: 0.000227

irrigation_nominal_cost: 0.001
nominal_water_level:     0.0
nominal_water_discharge: 0.0001

# Gurobi solver parameters
feasibility_tol: 0.001
optimality_tol: 0.001
solver_method: -1
